### ISSUE TITLE
chcp parsing is wrong for German locale

### ISSUE THREAD

**Issue by wngrtn** [junegunn/vim-plug#884]
PlugUpdate fails to update my plugins, but it doesn't show any error messages.

How do I diagnose this or make vim-plug give me more verbose error messages?

Here is the output I am getting:

```
Updated. Elapsed time: 4.042648 sec.
[xxxxxxxxxxxxxxxxxxxxxxxxxxxx]

- Finishing ... Done!
x vim-polyglot:
    OK
x fzf:
    OK
x vim-devicons:
    OK
x tagalong.vim:
    OK
```

(Concatenated, but it continues like this for all plugins.)

------------------------------

```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include

übersetzt    von appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM\sysinit.vim"
     Voreinstellung für $VIM: "   C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by flotisable** [comment]
I have a similar problem but it shows "PlugClean required" for each plugin.
And this happens only when I set the shell option to be **powershell**,
in cmd, it works as expected.
My neovim version is the same as @wngrtn .

**Comment by janlazo** [comment]
#886 is merged.

**Comment by wngrtn** [comment]
Sadly, #886 didn't fix the problem for me:

![grafik](https://user-images.githubusercontent.com/2025721/65877745-b1d58d80-e38c-11e9-8df4-e308ec32bf2a.png)

**Comment by janlazo** [comment]
String parsing is hard. Which language is this?

**Comment by wngrtn** [comment]
@janlazo, yes it is. This is German.

I am not sure what you mean by "What if `chcp` is not reverted back?" Do you want me to test something?

Is there a way to force the language to be English?

**Comment by janlazo** [comment]
@wngrtn I thought of running `chcp 65001 > nul` unconditionally and skip checking the current codepage. That breaks the codepage on the console where terminal Vim runs because terminal Vim runs `:!` on the current shell instead of spawning a new one. 

https://github.com/junegunn/vim-plug/pull/888 should fix this.

**Comment by janlazo** [comment]
Did the situation improve?

**Comment by flotisable** [comment]
My problem still exist
<img width="365" alt="註解 2019-10-04 094852" src="https://user-images.githubusercontent.com/22073008/66175433-34f82b80-e68c-11e9-8fbd-2148cd2df989.png">

My shell options
<img width="630" alt="註解 2019-10-04 095705" src="https://user-images.githubusercontent.com/22073008/66175734-5c032d00-e68d-11e9-8ecb-96f1c8d71029.png">

**Comment by janlazo** [comment]
I need the full list of shell options. You're missing `shellquote`, `shellxquote`, `shellxescape`, `shellpipe`.

**Comment by flotisable** [comment]
The three options are the default and the values are
```
shellquote=
shellxquote="
shellxescape=
```

and if I set `shellxquote` to be empty the result will be 
<img width="634" alt="註解 2019-10-04 164243" src="https://user-images.githubusercontent.com/22073008/66194073-570e9f80-e6c6-11e9-8723-2bf3c17b23a6.png">

I have simplified my init file to be
```
set runtimepath+=~/.vim,~/.vim/after
set packpath+=~/.vim

set shell=powershell
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
set shellpipe=\|
set shellredir=\|\ Out-File\ -Encoding\ UTF8
set shellquote=
set shellxquote=

call plug#begin( '~/.vim/plugged' )

  Plug 'scrooloose/nerdtree'
  Plug 'majutsushi/tagbar'
  Plug 'octol/vim-cpp-enhanced-highlight'

call plug#end()
```
and the result is the same

**Comment by janlazo** [comment]
The default values for shell options are meant for cmd.exe. They're incompatible with powershell. Now that `set shellquote=` is set, we have an error message so at least nvim can execute the shell. Batchfile failed to execute though.

**Comment by janlazo** [comment]
shell detection is more complicated now that `&shell` can be escaped if it contains a space. Happens on Vim since 8.0.1455 for `$SHELL`  and 8.1.2115 on Windows. Neovim will have this behavior eventually.

**Comment by janlazo** [comment]
Does `chcp` output a dot at end? fzf does not append a dot at the end of `Invalid URI` error message. Stripping out non-digit values should do the trick unless the codepage is non-numeric in another language.

**Comment by flotisable** [comment]
Sorry for the late replication.
I have update the vim-plug and the problem is still the same.
I forget to provide the error message before updating plugins
<img width="840" alt="註解 2019-10-17 104121" src="https://user-images.githubusercontent.com/22073008/66973558-e8b8dc80-f0ca-11e9-8212-4cdc6b57c7e1.png">

My main language is Traditional Chinese and there is not dot at the end of `chcp` output.
Maybe this is not related to this issue and I should create another issue?

**Comment by janlazo** [comment]
@flotisable Sure. Add your shell settings in the minimal vimrc.
